import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Login from './components/login'
import AuthSession from './session'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    icons : {
        icon : "/favicon.ico"
    }
}
export default async function RootLayout({
    children,
    }: {
    children: React.ReactNode
    }) {

    return (
        <html lang="en">
        <body className={inter.className}>
            <AuthSession>
                <Login />
                {children}
            </AuthSession>
        </body>
        </html>
    )
}

// 전체를 읽어내는 곳입니다. 여기는 Main이라고 생각하면 됩니다.